/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Pantallas;

import Controlador.ControladorCuentas;
import Controlador.ControladorIncio;
import Controlador.ControladorLibroDiario;

/**
 *
 * @author Marlo
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnlibrodiario = new javax.swing.JButton();
        btnlibromayor = new javax.swing.JButton();
        btnbalanzacomprobacion = new javax.swing.JButton();
        btnbalanzageneral = new javax.swing.JButton();
        btncatalogo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        btnlibrodiario.setText("Libro Diario");
        btnlibrodiario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibrodiarioActionPerformed(evt);
            }
        });

        btnlibromayor.setText("Libro Mayor");
        btnlibromayor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlibromayorActionPerformed(evt);
            }
        });

        btnbalanzacomprobacion.setText("Balance De Comprobación");
        btnbalanzacomprobacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbalanzacomprobacionActionPerformed(evt);
            }
        });

        btnbalanzageneral.setText("Balance General");

        btncatalogo.setText("Catalogo De Cuentas");
        btncatalogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncatalogoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnbalanzacomprobacion)
                                .addGap(18, 18, 18)
                                .addComponent(btnbalanzageneral))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnlibrodiario)
                                .addGap(46, 46, 46)
                                .addComponent(btnlibromayor))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(134, 134, 134)
                        .addComponent(btncatalogo)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnlibrodiario)
                    .addComponent(btnlibromayor))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnbalanzacomprobacion)
                    .addComponent(btnbalanzageneral))
                .addGap(30, 30, 30)
                .addComponent(btncatalogo)
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnlibrodiarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibrodiarioActionPerformed
       
    }//GEN-LAST:event_btnlibrodiarioActionPerformed

    private void btnlibromayorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlibromayorActionPerformed
        
    }//GEN-LAST:event_btnlibromayorActionPerformed

    private void btnbalanzacomprobacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbalanzacomprobacionActionPerformed
        
    }//GEN-LAST:event_btnbalanzacomprobacionActionPerformed

    private void btncatalogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncatalogoActionPerformed
      
    }//GEN-LAST:event_btncatalogoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Menu().setVisible(true);
                ControladorIncio crt = new ControladorIncio();
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnbalanzacomprobacion;
    public javax.swing.JButton btnbalanzageneral;
    public javax.swing.JButton btncatalogo;
    public javax.swing.JButton btnlibrodiario;
    public javax.swing.JButton btnlibromayor;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
